/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutmainImport } from './routes/_layoutmain'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutmainRegIndexImport } from './routes/_layoutmain/reg/index'
import { Route as LayoutmainProfileIndexImport } from './routes/_layoutmain/profile/index'
import { Route as LayoutmainParfumIndexImport } from './routes/_layoutmain/parfum/index'
import { Route as LayoutmainNaborIndexImport } from './routes/_layoutmain/nabor/index'
import { Route as LayoutmainDostavkaIndexImport } from './routes/_layoutmain/dostavka/index'
import { Route as LayoutmainContactIndexImport } from './routes/_layoutmain/contact/index'
import { Route as LayoutmainCarzinaIndexImport } from './routes/_layoutmain/carzina/index'
import { Route as LayoutmainCardInfoIndexImport } from './routes/_layoutmain/cardInfo/index'
import { Route as LayoutmainAuthIndexImport } from './routes/_layoutmain/auth/index'
import { Route as LayoutmainAromatIndexImport } from './routes/_layoutmain/aromat/index'
import { Route as LayoutmainAdminIndexImport } from './routes/_layoutmain/admin/index'

// Create/Update Routes

const LayoutmainRoute = LayoutmainImport.update({
  id: '/_layoutmain',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutmainRegIndexRoute = LayoutmainRegIndexImport.update({
  id: '/reg/',
  path: '/reg/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainProfileIndexRoute = LayoutmainProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainParfumIndexRoute = LayoutmainParfumIndexImport.update({
  id: '/parfum/',
  path: '/parfum/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainNaborIndexRoute = LayoutmainNaborIndexImport.update({
  id: '/nabor/',
  path: '/nabor/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainDostavkaIndexRoute = LayoutmainDostavkaIndexImport.update({
  id: '/dostavka/',
  path: '/dostavka/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainContactIndexRoute = LayoutmainContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainCarzinaIndexRoute = LayoutmainCarzinaIndexImport.update({
  id: '/carzina/',
  path: '/carzina/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainCardInfoIndexRoute = LayoutmainCardInfoIndexImport.update({
  id: '/cardInfo/',
  path: '/cardInfo/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAuthIndexRoute = LayoutmainAuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAromatIndexRoute = LayoutmainAromatIndexImport.update({
  id: '/aromat/',
  path: '/aromat/',
  getParentRoute: () => LayoutmainRoute,
} as any)

const LayoutmainAdminIndexRoute = LayoutmainAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutmainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layoutmain': {
      id: '/_layoutmain'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutmainImport
      parentRoute: typeof rootRoute
    }
    '/_layoutmain/admin/': {
      id: '/_layoutmain/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutmainAdminIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/aromat/': {
      id: '/_layoutmain/aromat/'
      path: '/aromat'
      fullPath: '/aromat'
      preLoaderRoute: typeof LayoutmainAromatIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/auth/': {
      id: '/_layoutmain/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LayoutmainAuthIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/cardInfo/': {
      id: '/_layoutmain/cardInfo/'
      path: '/cardInfo'
      fullPath: '/cardInfo'
      preLoaderRoute: typeof LayoutmainCardInfoIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/carzina/': {
      id: '/_layoutmain/carzina/'
      path: '/carzina'
      fullPath: '/carzina'
      preLoaderRoute: typeof LayoutmainCarzinaIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/contact/': {
      id: '/_layoutmain/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutmainContactIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/dostavka/': {
      id: '/_layoutmain/dostavka/'
      path: '/dostavka'
      fullPath: '/dostavka'
      preLoaderRoute: typeof LayoutmainDostavkaIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/nabor/': {
      id: '/_layoutmain/nabor/'
      path: '/nabor'
      fullPath: '/nabor'
      preLoaderRoute: typeof LayoutmainNaborIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/parfum/': {
      id: '/_layoutmain/parfum/'
      path: '/parfum'
      fullPath: '/parfum'
      preLoaderRoute: typeof LayoutmainParfumIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/profile/': {
      id: '/_layoutmain/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutmainProfileIndexImport
      parentRoute: typeof LayoutmainImport
    }
    '/_layoutmain/reg/': {
      id: '/_layoutmain/reg/'
      path: '/reg'
      fullPath: '/reg'
      preLoaderRoute: typeof LayoutmainRegIndexImport
      parentRoute: typeof LayoutmainImport
    }
  }
}

// Create and export the route tree

interface LayoutmainRouteChildren {
  LayoutmainAdminIndexRoute: typeof LayoutmainAdminIndexRoute
  LayoutmainAromatIndexRoute: typeof LayoutmainAromatIndexRoute
  LayoutmainAuthIndexRoute: typeof LayoutmainAuthIndexRoute
  LayoutmainCardInfoIndexRoute: typeof LayoutmainCardInfoIndexRoute
  LayoutmainCarzinaIndexRoute: typeof LayoutmainCarzinaIndexRoute
  LayoutmainContactIndexRoute: typeof LayoutmainContactIndexRoute
  LayoutmainDostavkaIndexRoute: typeof LayoutmainDostavkaIndexRoute
  LayoutmainNaborIndexRoute: typeof LayoutmainNaborIndexRoute
  LayoutmainParfumIndexRoute: typeof LayoutmainParfumIndexRoute
  LayoutmainProfileIndexRoute: typeof LayoutmainProfileIndexRoute
  LayoutmainRegIndexRoute: typeof LayoutmainRegIndexRoute
}

const LayoutmainRouteChildren: LayoutmainRouteChildren = {
  LayoutmainAdminIndexRoute: LayoutmainAdminIndexRoute,
  LayoutmainAromatIndexRoute: LayoutmainAromatIndexRoute,
  LayoutmainAuthIndexRoute: LayoutmainAuthIndexRoute,
  LayoutmainCardInfoIndexRoute: LayoutmainCardInfoIndexRoute,
  LayoutmainCarzinaIndexRoute: LayoutmainCarzinaIndexRoute,
  LayoutmainContactIndexRoute: LayoutmainContactIndexRoute,
  LayoutmainDostavkaIndexRoute: LayoutmainDostavkaIndexRoute,
  LayoutmainNaborIndexRoute: LayoutmainNaborIndexRoute,
  LayoutmainParfumIndexRoute: LayoutmainParfumIndexRoute,
  LayoutmainProfileIndexRoute: LayoutmainProfileIndexRoute,
  LayoutmainRegIndexRoute: LayoutmainRegIndexRoute,
}

const LayoutmainRouteWithChildren = LayoutmainRoute._addFileChildren(
  LayoutmainRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutmainRouteWithChildren
  '/admin': typeof LayoutmainAdminIndexRoute
  '/aromat': typeof LayoutmainAromatIndexRoute
  '/auth': typeof LayoutmainAuthIndexRoute
  '/cardInfo': typeof LayoutmainCardInfoIndexRoute
  '/carzina': typeof LayoutmainCarzinaIndexRoute
  '/contact': typeof LayoutmainContactIndexRoute
  '/dostavka': typeof LayoutmainDostavkaIndexRoute
  '/nabor': typeof LayoutmainNaborIndexRoute
  '/parfum': typeof LayoutmainParfumIndexRoute
  '/profile': typeof LayoutmainProfileIndexRoute
  '/reg': typeof LayoutmainRegIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutmainRouteWithChildren
  '/admin': typeof LayoutmainAdminIndexRoute
  '/aromat': typeof LayoutmainAromatIndexRoute
  '/auth': typeof LayoutmainAuthIndexRoute
  '/cardInfo': typeof LayoutmainCardInfoIndexRoute
  '/carzina': typeof LayoutmainCarzinaIndexRoute
  '/contact': typeof LayoutmainContactIndexRoute
  '/dostavka': typeof LayoutmainDostavkaIndexRoute
  '/nabor': typeof LayoutmainNaborIndexRoute
  '/parfum': typeof LayoutmainParfumIndexRoute
  '/profile': typeof LayoutmainProfileIndexRoute
  '/reg': typeof LayoutmainRegIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layoutmain': typeof LayoutmainRouteWithChildren
  '/_layoutmain/admin/': typeof LayoutmainAdminIndexRoute
  '/_layoutmain/aromat/': typeof LayoutmainAromatIndexRoute
  '/_layoutmain/auth/': typeof LayoutmainAuthIndexRoute
  '/_layoutmain/cardInfo/': typeof LayoutmainCardInfoIndexRoute
  '/_layoutmain/carzina/': typeof LayoutmainCarzinaIndexRoute
  '/_layoutmain/contact/': typeof LayoutmainContactIndexRoute
  '/_layoutmain/dostavka/': typeof LayoutmainDostavkaIndexRoute
  '/_layoutmain/nabor/': typeof LayoutmainNaborIndexRoute
  '/_layoutmain/parfum/': typeof LayoutmainParfumIndexRoute
  '/_layoutmain/profile/': typeof LayoutmainProfileIndexRoute
  '/_layoutmain/reg/': typeof LayoutmainRegIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/aromat'
    | '/auth'
    | '/cardInfo'
    | '/carzina'
    | '/contact'
    | '/dostavka'
    | '/nabor'
    | '/parfum'
    | '/profile'
    | '/reg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/admin'
    | '/aromat'
    | '/auth'
    | '/cardInfo'
    | '/carzina'
    | '/contact'
    | '/dostavka'
    | '/nabor'
    | '/parfum'
    | '/profile'
    | '/reg'
  id:
    | '__root__'
    | '/'
    | '/_layoutmain'
    | '/_layoutmain/admin/'
    | '/_layoutmain/aromat/'
    | '/_layoutmain/auth/'
    | '/_layoutmain/cardInfo/'
    | '/_layoutmain/carzina/'
    | '/_layoutmain/contact/'
    | '/_layoutmain/dostavka/'
    | '/_layoutmain/nabor/'
    | '/_layoutmain/parfum/'
    | '/_layoutmain/profile/'
    | '/_layoutmain/reg/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutmainRoute: typeof LayoutmainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutmainRoute: LayoutmainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_layoutmain"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_layoutmain": {
      "filePath": "_layoutmain.jsx",
      "children": [
        "/_layoutmain/admin/",
        "/_layoutmain/aromat/",
        "/_layoutmain/auth/",
        "/_layoutmain/cardInfo/",
        "/_layoutmain/carzina/",
        "/_layoutmain/contact/",
        "/_layoutmain/dostavka/",
        "/_layoutmain/nabor/",
        "/_layoutmain/parfum/",
        "/_layoutmain/profile/",
        "/_layoutmain/reg/"
      ]
    },
    "/_layoutmain/admin/": {
      "filePath": "_layoutmain/admin/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/aromat/": {
      "filePath": "_layoutmain/aromat/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/auth/": {
      "filePath": "_layoutmain/auth/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/cardInfo/": {
      "filePath": "_layoutmain/cardInfo/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/carzina/": {
      "filePath": "_layoutmain/carzina/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/contact/": {
      "filePath": "_layoutmain/contact/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/dostavka/": {
      "filePath": "_layoutmain/dostavka/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/nabor/": {
      "filePath": "_layoutmain/nabor/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/parfum/": {
      "filePath": "_layoutmain/parfum/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/profile/": {
      "filePath": "_layoutmain/profile/index.jsx",
      "parent": "/_layoutmain"
    },
    "/_layoutmain/reg/": {
      "filePath": "_layoutmain/reg/index.jsx",
      "parent": "/_layoutmain"
    }
  }
}
ROUTE_MANIFEST_END */
